# ==========================================
# DEATHSWAP CONFIG
# ==========================================

# DeathSwap ke har swap ke beech ka time.
# 300 = 5 minutes
# 600 = 10 minutes
# 60  = 1 minute
swap-time-seconds: 300

# Game start hone se pehle countdown.
start-countdown-seconds: 3

# Kitne points par team winner hogi.
points-to-win: 3


# ==========================================
# MESSAGES
# ==========================================

messages:

  # Har message ke beginning mein ye prefix aayega.
  prefix: "&8[&cDeathSwap&8] &r"