# ==========================================
# DEATHSWAP CONFIG
# ==========================================

# Time between each DeathSwap, in seconds.
# 300 = 5 minutes
# 600 = 10 minutes
# 60  = 1 minute
swap-time-seconds: 300

# Countdown before the game starts.
start-countdown-seconds: 3

# Points required for a team to win.
points-to-win: 3

# ==========================================
# MESSAGES
# ==========================================

messages:

  # Prefix added to plugin messages.
  prefix: "&8[&cDeathSwap&8] &r"
